### PR TITLE
repository.owner.name -> repository.owner.login

### LINKED ISSUE #25: KeyError 'name' ('repository.owner.name')
I'm having an issue where I get a 500 error on push events, the problem is that the payload does not include a `name` parameter for the `owner` of the repository in question.  See the screenshot here for the payload data:

image

I have forked the repository and I am doing some work there to see if I can use this at work to replace our external CI system, I'll make a patch there to rely on `repository.owner.login` if name can not be found.

Why `name` is missing for me is unclear, the account in question is mine and I have my full name set.

### PR DESCRIPTION
**Pull request by steinnes**
This should fix #25

### CODE REVIEW

**Comment by steinnes** [comment]
I did this change separately from master, but I have some more goodies on another branch locally.  Mostly docker support (I have an ubuntu 14.04 based linux machine which I am using for development, so I decided to write the Dockerfile to be able to work with flux from ubuntu 16.04 for a newer, supported, git version).

I am having some other issues with GitHub... I'll show you @NiklasRosenstein when I'm done and we can see if you want to merge any of those changes.

**Comment by NiklasRosenstein** [comment]
Just to check since you said "should fix": Were you able to verify that it's working now? I can't test it atm.

**Comment by NiklasRosenstein** [comment]
> Mostly docker support

Awesome! :grin: Looking forward to that, thanks.

**Comment by steinnes** [comment]
The change on my branch is slightly different, I'll test this one there and let you know!

**Comment by steinnes** [comment]
Ok, glad you asked about whether I tested that, because I just did and the payload seems different based on the type of event from GitHub (or something).  This branch breaks in other scenarios.

image

**Comment by steinnes** [comment]
This version has been tested.  I'm rebasing the docker branch to use it (as the docker branch is the one I am able to test easily here at home ;-).

**Comment by steinnes** [comment]
This was my misunderstanding, I didn't see anywhere that only *push* events were supported, and the existing code seems fine for those.  Let's skip this since flux does not support other events (and it's not even particularly straight forward to detect the event type, at first glance).

**Pull request closed without merging**
